language: android
jdk: oraclejdk8
android:
  components:
    - platform-tools
    - tools
    - build-tools-27.1.1
    - android-27

before_install:
    - yes | sdkmanager "platforms;android-27"

script:
  - ./gradlew clean
  - ./gradlew build
  
